/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class UIView;

@interface UIViewHeartbeat : NSObject
{
    UIView *_view;
    SEL _selector;
    struct __GSHeartbeat *_heartbeat;
}

+ (void)startHeartbeatWithView:(id)fp8 selector:(SEL)fp12 inRunLoopMode:(id)fp16;	// IMP=0x323c3630
+ (void)stopHeartbeatWithView:(id)fp8 selector:(SEL)fp12;	// IMP=0x323c3764
- (void)dealloc;	// IMP=0x323c35c8

@end

